### ISSUE TITLE
Tracker for pre-built dynamic modules and grammars for Apple Silicon (M1)

### ISSUE THREAD

**Issue by ubolonton** [emacs-tree-sitter/elisp-tree-sitter#197]
- [x] Update CI to publish artifacts with platform in file names.
  + [x] `tsc-dyn`: https://github.com/emacs-tree-sitter/elisp-tree-sitter/commit/48b06796a3b2e76ce004972d929de38146eafaa0
  + [x] Compiled grammars: https://github.com/emacs-tree-sitter/tree-sitter-langs/commit/325b83c60cca3933252c15bf7c60d4f5206d39e6
- [x] Update CI to publish artifacts for `aarch64-apple-darwin`.
  + [x] `tsc-dyn`: https://github.com/emacs-tree-sitter/elisp-tree-sitter/commit/48b06796a3b2e76ce004972d929de38146eafaa0
  + [x] Compiled grammars: https://github.com/emacs-tree-sitter/tree-sitter-langs/commit/be048aa2a71d9a25c855d6d2abbf46f72b6b8ac9
- [x] Update binary downloading code to handle different platforms.
  + #206
  + https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/73

This will fix #88. Related: #166 and https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/36

**Comment by ubolonton** [comment]
Binaries for Apple Silicon are available starting from [elisp-tree-sitter 0.16.1](https://github.com/emacs-tree-sitter/elisp-tree-sitter/releases/tag/0.16.1) and [tree-sitter-langs 0.10.13](https://github.com/emacs-tree-sitter/tree-sitter-langs/releases/tag/0.10.13).

**Comment by wyuenho** [comment]
I'm on an M1 Pro, but I don't seem to be able to fetch the correct prebuilt binary when installing from package.el

```
Compiling file /Users/wyuenho/.emacs.d/elpa/tree-sitter-20211211.1220/tree-sitter.el at Sat Dec 18 01:30:01 2021
tree-sitter.el:22:1: Error: Module could not be opened: "/Users/wyuenho/.emacs.d/elpa/tsc-20211211.1220/tsc-dyn.dylib", "dlopen(/Users/wyuenho/.emacs.d/elpa/tsc-20211211.1220/tsc-dyn.dylib, 0x0001): tried: '/Users/wyuenho/.emacs.d/elpa/tsc-20211211.1220/tsc-dyn.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/tsc-dyn.dylib' (no such file), '/usr/lib/tsc-dyn.dylib' (no such file)"
```

**Comment by wyuenho** [comment]
Looks like `tsc-dyn-get--download` wasn't updated to reflect the latest binary naming scheme.

**Comment by evolify** [comment]
Still not work

**Comment by brurucy** [comment]
Still not working^2 m1 pro

**Comment by theHamsta** [comment]
I think it would be good to create a standardized GitHub workflow action that would parsers developers to publish for all relevant platforms. The problem of cross-compling for arm64 would then only have to be solved once for all parser consumers.

**Comment by jeremyf** [comment]
With PR #206, I was able to get past the compile error

I use straight.el and did the following:

- Remove the repos and builds from the straight.el build directory
- Updated my straight tree-sitter to install from Github
- Restarted my emacs daemon

**Comment by ckruse** [comment]
Great work! Thank you very much!

**Comment by jeremyf** [comment]
Yes, great work and thank you.  TreeSitter highlighting adds just a bit more context to Ruby syntax highlighting.
